### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by MartinaRuocco** [ascentai/diy-gym#31]
This repo seems fantastic! I am planning to test it extensively in the next few days! 

I see that it was created 2 years ago, though. Is this project still active?
Also, did you publish this work on a paper/medium article?

All the best

**Comment by thomascent** [comment]
Hi @MartinaRuocco! Really sorry for the slow reply. I'm glad you like the repo! Unfortunately as you might have guessed we haven't been actively working on this for a while, but that said the repo should be in a relatively stable condition (not counting those problems you had with installation in the other issue) and now that it's back on my radar I'd be happy to help you out with any problems you might encounter while using it.

This issue is a little old now so perhaps you've already moved on but if not, by all means make issues / PRs for anything you like!

**Comment by MartinaRuocco** [comment]
Hi @thomascent 
Very cool to know that you're back on the radar! I've been meaning to use this repo in the next weeks so I'm glad to know that this repo is active again!! 
Many thanks

**Comment by MartinaRuocco** [comment]
hey there again @thomascent 
did you try to run some Reinforcement Learning training using your environments? 
I'm having some trouble adapting the diy_gym envs to the stable_baselines agents.

**Comment by thomascent** [comment]
Hey @MartinaRuocco, I don't think I ever used any agents from `stable_baselines`, but I have tested the envs using some agents that I wrote myself as well as [this implementation of TD3](https://github.com/sfujim/TD3). If you're still having troubles would you be able to create a separate issue describing the problem? I can help you work though it there
